name: Coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v6

      - name: Set up Python 3.10
        uses: actions/setup-python@v6
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install flake8 pytest
      - name: Run core coverage
        run: |
          pip install .[tests]
          python -m pytest --verbose --cov emukit --cov-report term-missing tests
      - name: Run GPy coverage
        run: |
          pip install ".[tests, gpy]"
          # work around issues with GPy setting matplotlib backend
          echo 'backend: Agg' > matplotlibrc
          python -m pytest  -m 'gpy or not gpy' --verbose --cov emukit --cov-report term-missing tests
      - name: Run codecov
        if: success()
        run: |
          codecov